api/urls.py
from django.urls import path
from .views import user_list, user_detail, task_list, task_detail

app_name = 'users'

urlpatterns = [
    path('users/', user_list, name='user_list'),
    path('users/<int:pk>/', user_detail, name='user_detail'),
    path('tasks/', task_list, name='task_list'),
    path('tasks/<int:pk>/', task_detail, name='task_detail'),
]

login/urls.py
from django.urls import path
from .views import LoginView, DetailUser, LogoutView, RegisterView, create_task, update_task, delete_task

app_name = 'consumer'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('detail_user/<int:pk>/', DetailUser.as_view(), name='detail_user'),
    path('create_task/', create_task, name='create_task'),
    path('update_task/<int:pk>', update_task, name='update_task'),
    path('delete_task/<int:pk>', delete_task, name='delete_task'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('login.urls')),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from api.models import User, Task


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username',
                               max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Enter Your username'}))
    password = forms.CharField(label='Password',
                               max_length=30,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Enter Your password'}))

class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Username',
                               max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Enter Your username'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': 'Enter your email'}))
    first_name = forms.CharField(label='First Name',
                                 max_length=30,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control',
                                            'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(label='Last Name',
                                max_length=30,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control',
                                           'placeholder': 'Enter your last name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CreateTask(forms.ModelForm):
    title = forms.CharField(label='Title',
                            max_length=30,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control',
                                       'placeholder': 'Enter your title'}))
    complete = forms.BooleanField(label='Complete',
                                    required=False,
                                    widget=forms.CheckboxInput(
                                        attrs={'class': 'form-check-input',
                                               'type': 'checkbox',
                                               'role': 'switch',
                                               'id': 'flexSwitchCheckDefault'}))
    date = forms.DateField(label='End Date',
                               widget=forms.DateInput(
                                   attrs={'class': 'form-control input-element',
                                          'placeholder': 'YYYY-MM-DD'}))

    class Meta:
        model = Task
        fields = ('title', 'complete', 'date')

login/views.py
from django.shortcuts import render, redirect
from api.models import User, Task
from django.views.generic import FormView, CreateView, DetailView, RedirectView
from .forms import LoginForm, RegisterForm, CreateTask
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .tasks import send_email


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'consumer/login.html'
    success_url = reverse_lazy('consumer:detail_user')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            send_email(user)
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('consumer:detail_user', kwargs={'pk': self.request.user.pk})


class DetailUser(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'consumer/detail_user.html'

    def get_context_data(self, **kwargs):
        context = super(DetailUser, self).get_context_data(**kwargs)
        user = User.objects.get(pk=self.request.user.pk)
        tasks = Task.objects.filter(user=user)
        context['user'] = user
        context['tasks'] = tasks
        return context


class LogoutView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('consumer:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class RegisterView(CreateView):
    form_class = RegisterForm
    model = User
    template_name = 'consumer/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.save()
        return super(RegisterView, self).form_valid(form)


@login_required
def create_task(request):
    if request.method == 'POST':
        form = CreateTask(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect(reverse_lazy('consumer:detail_user', kwargs={'pk': request.user.pk}))
    else:
        form = CreateTask()
    return render(request, 'consumer/create_task.html', {'form': form})


@login_required
def update_task(request, pk):
    task = Task.objects.get(pk=pk)
    if request.method == 'POST':
        form = CreateTask(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect(reverse_lazy('consumer:detail_user', kwargs={'pk': request.user.pk}))
    else:
        form = CreateTask(instance=task)
    return render(request, 'consumer/create_task.html', {'form': form})

@login_required
def delete_task(request, pk):
    task = Task.objects.get(pk=pk)
    task = task.delete()
    return redirect(reverse_lazy('consumer:detail_user', kwargs={'pk': request.user.pk}))

templates/consumer/create_task.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <h1 class="text-center mt-4">Add Task</h1>
    <form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success mt-2 button">Create</button>
</form>
</div>

{% endblock %}
{% block js %}
<script>

let cleave = new Cleave('.input-element', {
    date: true,
    delimiter: '-',
    datePattern: ['Y', 'm', 'd']
});


</script>
{% endblock %}

templates/consumer/detail_user.html
{% extends 'base.html' %}
{% block title %} {{user.username|capfirst}} {% endblock %} 
{% load static %}
{% block content%}
{% include 'consumer/navbar.html' %}
<div class="container">
    <h1 class="text-center mt-3 mb-5">Welcome {{user.username}}</h1>
</div>
{% if tasks %}
<div class="container">
  <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Complete?</th>
      <th scope="col">Date</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
        <tr>
            <th scope="row">{{task.id}}</th>
            <td>{{task.title}}</td>
            {% if task.complete %}
              <td><span class="badge bg-success">Yes</span></td>
            {% else %}
              <td><span class="badge bg-danger">No</span></td>
            {% endif %}
            <td>@{{task.date}}</td>
            <td><a href="{% url 'consumer:update_task' task.id %}" class="btn btn-info">Update</a></td>
            <td><a href="{% url 'consumer:delete_task' task.id %}" class="btn btn-danger">Delete</a></td>
        </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<h3 class="text-center mb-5">No hay tareas</h3>
{% endif %}
{% endblock %}

templates/consumer/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5 mb-4 p-5 rounded-3 col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 col-xxl-6" id="form-login">
        <h1 class="text-center">Welcome new user</h1>
        {% load crispy_forms_tags %}
        <form action="{% url 'consumer:login' %}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-success w-25 mt-4">Login</button>
                <a href="{% url 'consumer:register' %}"class="btn btn-primary w-25 mt-4">Register</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/consumer/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <div class="d-flex align-items-center gap-4">
        <h1 class="navbar-brand">{{user.username|capfirst}}</h1>
    </div>
    <div class="navbar-nav d-flex flex-row gap-3">
        <a href="{% url 'consumer:logout' %}" class="btn btn-danger">Logout</a>
        <a href="{% url 'consumer:create_task' %}" class="btn btn-primary">Add Task</a>
    </div>
  </div>
</nav>

templates/consumer/register.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block content %}
    <div class="container mt-5 mb-4 p-5 rounded-3 width_custom col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 col-xxl-6" id="form-login">
        <h1 class="text-center">Welcome new user</h1>
        {% load crispy_forms_tags %}
        <form action="{% url 'consumer:register' %}" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-success w-25 mt-4">Register</button>
                <a href="{% url 'consumer:login' %}"class="btn btn-primary w-25 mt-4">Login</a>
            </div>
        </form>
    </div>
{% endblock %}